name: 'Deploy'

on:
    push:
        branches:
          - master

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
          - name: Checkout
            uses: actions/checkout@master

          - name: Setup Node
            uses: actions/setup-node@v3
            with:
                node-version: 18

          - name: Setup Pnpm
            uses: pnpm/action-setup@v2
            with:
                version: 7
                run_install: |
                  - args: [--frozen-lockfile]

          - name: Build
            run: |
                pnpm run build

          - name: Generate Icon
            run: |
                pnpm run icon

          - name: Setup Pages
            uses: actions/configure-pages@v2

          - name: Upload artifact
            uses: actions/upload-pages-artifact@v1
            with:
                path: './dist'

          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v1
